defaults:
  - mode: train # dev or train
  - optimizer: adamw
  - _self_

seed: 0
device: cuda
num_workers: 1

# Data
data_dir: data
experiment_name: ${mode.mode}mode_run_beta1${optimizer.beta1}_beta2${optimizer.beta2}_seed${seed}
output_dir: experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}_${experiment_name}
data:
  seed: 0

# Weights and Biases (used for logging)
wandb:
  enabled: true
  project: nn_optimization_similarity
  mode: offline

# Hydra (used for output)
hydra:
  run:
    dir: ${output_dir}