defaults:
  - mode: dev # dev or train
  - optimizer: adam_atan2
  - _self_

seed: 10
device: cuda
num_workers: 4

# Data
data_dir: data
experiment_name: ${mode.mode}mode_run_optimizer_${optimizer.name}_seed${seed}
output_dir: experiments/${experiment_name}

# Similarity Analysis
state: epoch # final or epoch

net_1:
  optimizer: adam_atan2
  seed: 10

net_2:
  optimizer: adam_atan2
  seed: 10

sim_metric: cka

# Visualization
file_pt: final # epoch_n or final
which_plot: 1 # used in scripts/analysis_plots.py

# Weights and Biases (used for logging)
wandb:
  enabled: true
  project: nn_optimization_similarity
  mode: offline

# Hydra (used for output)
hydra:
  run:
    dir: ${output_dir}