defaults:
  - mode: dev # dev or train
  - optimizer: adam_atan2
  - _self_

seed: 0
device: cuda
num_workers: 8

model:
  activation: relu

# Data
data_dir: data
experiment_name: ${mode.mode}mode_run_bs${mode.training.batch_size}_lr${optimizer.lr}_epochs${mode.training.epochs}_seed${seed}
output_dir: experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}_${experiment_name}
data:
  seed: 0

# Weights and Biases (used for logging)
wandb:
  enabled: true
  project: nn_optimization_similarity
  mode: offline

# Hydra (used for output)
hydra:
  run:
    dir: ${output_dir}